### ISSUE TITLE
Проблема с портами 

### ISSUE THREAD

**Issue by Lamers5544** [mishakorzik/open-port#1]
Прописываю: open 8080
Пишет что такой порт открыт.
Прописываю: close 8080
Пишет что такой порт закрыт.
Установил данную утилиту в Termux.
День назад программа работала идеально.
Помогите пожалуйста.

**Comment by mishakorzik** [comment]
Привет, програма иногда может не работать из-за того что бесплатный serveo.net иногда не работает.
